name: Manual Builds Custom

on: 
  workflow_dispatch:
  
    inputs:
      buildosflavor:
        description: 'centos7 / centos8 / fedora / ubuntu / debian'
        required: true
        options: ['centos7', 'centos8', 'fedora', 'ubuntu', 'debian']
        default: 'fedora'
     
      branchesflavor:
        description: 'Select the Gluster Branch'
        required: true
        options: ['devel', 'v10.1', 'v9.5']
        default: 'devel'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             ./Setup_Host.sh
    
    - name: Cleanup Old Docker images if any
      run:  docker system prune -af
      
    - name: Selecting build based on OS flavour
      run: |
            if [[ "${{ github.event.inputs.buildosflavor }}" == "centos7" ]]; then
              - name: Build from Dockerfile
                run: |
                  cp startscript-centos7.sh Docker/Centos7/
                  cd Docker/Centos7
                  docker build -t gluster-build .  
              - name: Running Build in Centos7 Container
                run: docker run --name container_gluster -v /build-out:/out gluster-build "${{ github.event.inputs.branchesflavor }}"
            fi
            
            if [[ "${{ github.event.inputs.buildosflavor }}" == "centos8" ]]; then
                - name: Build from Dockerfile
                  run: |
                      cp startscript.sh Docker/Centos8/
                      cd Docker/Centos8
                      docker build -t gluster-build .
               - name: Running Build in Centos8 Container
                 run: docker run --name container_gluster -v /build-out:/out gluster-build
            fi
            
            if [[ "${{ github.event.inputs.buildosflavor }}" == "fedora" ]]; then
              - name: Build from Dockerfile
                run: |
                    cp startscript.sh Docker/Fedora/
                    cd Docker/Fedora
                    docker build -t gluster-build .
              - name: Running Build in Fedora Container
                run: docker run --name container_gluster -v /build-out:/out gluster-build
            fi
            
            if [[ "${{ github.event.inputs.buildosflavor }}" == "ubuntu" ]]; then
              - name: Build from Dockerfile
                run: |
                    cp build.sh Docker/Ubuntu/
                    cd Docker/Ubuntu
                    docker build -t gluster-build .
              - name: Running Build in ubuntu Container
                run:  docker run --security-opt seccomp=unconfined --name container_gluster -v /build-out:/out gluster-build
            fi
            if [[ "${{ github.event.inputs.buildosflavor }}" == "debian" ]]; then
              - name: Build from Dockerfile
                run: |
                    cp build.sh Docker/Debian/
                    cd Docker/Debian
                    docker build -t gluster-build .
              - name: Running Build in debian Container
                run:  docker run --security-opt seccomp=unconfined --name container_gluster -v /build-out:/out gluster-build
            fi
