name: Manual Builds Custom

on: 
  workflow_dispatch:
  
    inputs:
      buildosflavor:
        description: 'centos7 / centos8 / fedora / ubuntu / debian'
        required: true
        options: ['centos7', 'centos8', 'fedora', 'ubuntu', 'debian']
        default: 'fedora'
     
      branchesflavor:
        description: 'Select the Gluster Branch: eg:- devel, v10.1, v9.5,v8.6'
        required: true
        options: ['devel', 'v10.1', 'v9.5']
        default: 'devel'

env:
  BRANCH: "${{ github.event.inputs.branchesflavor }}"
  
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             ./Setup_Host.sh
    
    - name: Cleanup Old Docker images if any
      run:  docker system prune -af
      
    - name: Selecting build based on OS flavour
      run: |
            if [[ "${{ github.event.inputs.buildosflavor }}" == "centos7" ]]; then
                  cp startscript-centos7.sh Docker/Centos7/
                  cd Docker/Centos7
                  docker build -t gluster-build .  
                  docker run --name container_gluster -v /build-out:/out gluster-build $BRANCH
            fi
            
            if [[ "${{ github.event.inputs.buildosflavor }}" == "centos8" ]]; then
                  cp startscript.sh Docker/Centos8/
                  cd Docker/Centos8
                  docker build -t gluster-build .
                  run: docker run --name container_gluster -v /build-out:/out gluster-build $BRANCH
            fi
            
            if [[ "${{ github.event.inputs.buildosflavor }}" == "fedora" ]]; then
                    cp startscript.sh Docker/Fedora/
                    cd Docker/Fedora
                    docker build -t gluster-build .
                    run: docker run --name container_gluster -v /build-out:/out gluster-build $BRANCH
            fi
            
            if [[ "${{ github.event.inputs.buildosflavor }}" == "ubuntu" ]]; then
                    cp build.sh Docker/Ubuntu/
                    cd Docker/Ubuntu
                    docker build -t gluster-build .
                    run:  docker run --security-opt seccomp=unconfined --name container_gluster -v /build-out:/out gluster-build $BRANCH
            fi
            
            if [[ "${{ github.event.inputs.buildosflavor }}" == "debian" ]]; then
                    cp build.sh Docker/Debian/
                    cd Docker/Debian
                    docker build -t gluster-build .
                    run:  docker run --security-opt seccomp=unconfined --name container_gluster -v /build-out:/out gluster-build $BRANCH
            fi
    
    - name: Upload Artifactory
      uses: actions/upload-artifact@v2
      with:
          name: gluster-rpms
          path: /build-out/*.rpm
          retention-days: 3
